174,1
S,UnitsWithSigns,Computes all units in O modulo squares such that the sign of the i-th real place in oo equals Signs[i],3,0,1,215,0,319,1,1,82,0,332,2,1,82,0,148,3,0,0,0,0,0,0,0,82,,0,0,82,,0,0,215,,82,-38,-38,-38,-38,-38
S,UnitsWithSigns,Computes all units in O modulo squares such that the sign of the i-th real place in oo equals Signs[i],2,1,1,82,0,332,2,1,82,0,148,3,0,0,0,0,0,0,0,82,,0,0,82,,0,0,-9,,82,-38,-38,-38,-38,-38
S,UnitsWithSigns,Computes all units in O modulo squares such that the sign of the i-th real place in oo equals Signs[i],2,1,1,82,0,147,2,1,82,0,148,3,0,0,0,0,0,0,0,82,,0,0,82,,0,0,319,,82,-38,-38,-38,-38,-38
S,UnitsWithSigns,Computes all units in O modulo squares such that the sign of the i-th real place in oo equals Signs[i],2,1,1,82,0,147,2,1,82,0,148,3,0,0,0,0,0,0,0,82,,0,0,82,,0,0,262,,82,-38,-38,-38,-38,-38
S,UnitsWithSigns,Computes all units in O modulo squares that have the same signs as x at all real places of O,1,0,1,215,0,319,2,0,0,0,0,0,0,0,-45,,0,0,215,,36,82,-38,-38,-38,-38
S,UnitsWithSigns,Computes all units in O modulo squares that have the same signs as x at all real places of O,0,2,0,0,0,0,0,0,0,-45,,0,0,-9,,82,-38,-38,-38,-38,-38
S,UnitsWithSigns,Computes all units in O modulo squares that have the same signs as x at all real places of O,0,2,0,0,0,0,0,0,0,-45,,0,0,319,,82,-38,-38,-38,-38,-38
S,UnitsWithSigns,Computes all units in O modulo squares that have the same signs as x at all real places of O,0,2,0,0,0,0,0,0,0,-45,,0,0,262,,82,-38,-38,-38,-38,-38
S,UnitsWithSigns,"Given an element x in an order or number field O, computes all units of O modulo squares that have the same signs as x at all real places of O",1,0,1,216,0,319,1,0,0,0,0,0,0,0,216,,82,-38,-38,-38,-38,-38
S,UnitsWithSigns,"Given an element x in an order or number field O, computes all units of O modulo squares that have the same signs as x at all real places of O",0,1,0,0,0,0,0,0,0,-10,,82,-38,-38,-38,-38,-38
S,UnitsWithSigns,"Given an element x in an order or number field O, computes all units of O modulo squares that have the same signs as x at all real places of O",0,1,0,0,0,0,0,0,0,267,,82,-38,-38,-38,-38,-38
S,UnitsWithSigns,"Given an element x in an order or number field O, computes all units of O modulo squares that have the same signs as x at all real places of O",0,1,0,0,0,0,0,0,0,148,,82,-38,-38,-38,-38,-38
S,HasTotallyPositiveGenerator,"Check if I can be generated by some totally positive element. If so, the second return value is the list of all such generators modulo unit squares",0,1,0,0,0,0,0,0,0,324,,36,82,-38,-38,-38,-38
