174,1
S,PSL2,"The projective special linear matrix group PSL(2,R)",0,1,0,0,0,0,0,0,0,-44,,GrpPSL2,-38,-38,-38,-38,-38
S,CongruenceSubgroup,"Given A = [n,m,p], this returns the congruence subgroup consisting of 2 by 2 matrices with integer coefficients [a,b,c,d] with a = d = 1 mod m, b = 0 mod p, and c = 0 mod n",0,1,0,0,0,0,0,0,0,82,,GrpPSL2,-38,-38,-38,-38,-38
S,CongruenceSubgroup,"Given N = [n,m,p], this returns the congruence subgroup consisting of 2 by 2 matrices with integer coefficients [a,b,c,d] with b = 0 mod p, and c = 0 mod n, and char(a) = 1 for char a Dirichlet character mod m",0,2,0,0,0,0,0,0,0,GrpDrchElt,,0,0,82,,GrpPSL2,-38,-38,-38,-38,-38
S,CongruenceSubgroup,"The congruence subgroup Gamma_0(N), Gamma_1(N), Gamma(N), Gamma^1(N), or Gamma^0(N), when k = 0,1,2,3, or 4 respectively",0,2,0,0,0,0,0,0,0,148,,0,0,148,,GrpPSL2,-38,-38,-38,-38,-38
S,CongruenceSubgroup,The full projective congruence subgroup Gamma(N),0,1,0,0,0,0,0,0,0,148,,GrpPSL2,-38,-38,-38,-38,-38
S,Gamma0,creates the congruence subgroup Gamma_0(N),0,1,0,0,0,0,0,0,0,148,,GrpPSL2,-38,-38,-38,-38,-38
S,Gamma1,creates the congruence subgroup Gamma_1(N),0,1,0,0,0,0,0,0,0,148,,GrpPSL2,-38,-38,-38,-38,-38
S,GammaUpper0,creates the congruence subgroup Gamma^0(N),0,1,0,0,0,0,0,0,0,148,,GrpPSL2,-38,-38,-38,-38,-38
S,GammaUpper1,creates the congruence subgroup Gamma^1(N),0,1,0,0,0,0,0,0,0,148,,GrpPSL2,-38,-38,-38,-38,-38
S,GammaNS,"creates the congruence subgroup Gamma_ns(N), choosing u as the nonsquare such that N | a-d, N | b-uc",0,2,0,0,0,0,0,0,0,321,,0,0,148,,GrpPSL2,-38,-38,-38,-38,-38
S,GammaNS,creates the congruence subgroup Gamma_ns(N),0,1,0,0,0,0,0,0,0,148,,GrpPSL2,-38,-38,-38,-38,-38
S,GammaNSplus,creates the congruence subgroup Gamma_ns^plus(N),0,2,0,0,0,0,0,0,0,321,,0,0,148,,GrpPSL2,-38,-38,-38,-38,-38
S,GammaNSplus,creates the congruence subgroup Gamma_ns^plus(N),0,1,0,0,0,0,0,0,0,148,,GrpPSL2,-38,-38,-38,-38,-38
S,/,Currently assumes the same level,0,2,0,0,0,0,0,0,0,GrpPSL2,,0,0,GrpPSL2,,GrpPSL2,-38,-38,-38,-38,-38
S,Normalizer,The normalizer of a congruence subgroup in SL_2(R),0,1,0,0,0,0,0,0,0,GrpPSL2,,GrpPSL2,-38,-38,-38,-38,-38
S,MaximalNormalizingWithAbelianQuotient,,0,1,0,0,0,0,0,0,0,GrpPSL2,,GrpPSL2,-38,-38,-38,-38,-38
S,Random,"returns a random element of the projective linear group G, m determines the size of the coefficients",0,2,0,0,0,0,0,0,0,148,,0,0,GrpPSL2,,GrpPSL2Elt,-38,-38,-38,-38,-38
S,Conjugate,This function returns the conjugation of G by A. At the moment we only support the case where both input and output are subgroups of PSL2(Z),0,2,0,0,0,0,0,0,0,180,,0,0,GrpPSL2,,GrpPSL2,-38,-38,-38,-38,-38
S,Intersection,returns the intersection of two congruence subgroups,0,2,0,0,0,0,0,0,0,GrpPSL2,,0,0,GrpPSL2,,GrpPSL2,-38,-38,-38,-38,-38
S,meet,returns the intersection of two congruence subgroups,0,2,0,0,0,0,0,0,0,GrpPSL2,,0,0,GrpPSL2,,GrpPSL2,-38,-38,-38,-38,-38
S,calcLevel,calculates the level of a subgroup of PSL2,0,1,0,0,0,0,0,0,0,GrpPSL2,,148,-38,-38,-38,-38,-38
S,SubgroupFromGens,returns the subgroup of G generated by gens,0,4,0,0,0,0,0,0,0,36,,0,0,148,,0,0,82,,0,0,GrpPSL2,,GrpPSL2,-38,-38,-38,-38,-38
S,PSL2SubgroupFromGens,returns the subgroup of PSL2(R) generated by gens,0,4,0,0,0,0,0,0,0,36,,0,0,148,,0,0,-44,,0,0,82,,GrpPSL2,-38,-38,-38,-38,-38
S,FindLiftToSL2,finds a lift in SL2 for g,0,1,0,0,0,0,0,0,0,180,,GrpPSL2Elt,-38,-38,-38,-38,-38
S,SubgroupFromMod,returns the subgroup of G generated whose image is H0,0,4,0,0,0,0,0,0,0,36,,0,0,178,,0,0,148,,0,0,GrpPSL2,,GrpPSL2,-38,-38,-38,-38,-38
S,PSL2Subgroup,returns a subgroup of PSL2(Z) whose image is H (assumes -I in H),0,2,0,0,0,0,0,0,0,36,,0,0,178,,GrpPSL2,-38,-38,-38,-38,-38
S,PSL2Subgroup,returns a subgroup of PSL2(Z) whose image is H (assumes -I in H),0,1,0,0,0,0,0,0,0,178,,GrpPSL2,-38,-38,-38,-38,-38
S,PSL2Subgroup,returns a subgroup of PSL2(Z) whose image is H (assumes -I in H),0,2,0,0,0,0,0,0,0,298,,0,0,178,,GrpPSL2,-38,-38,-38,-38,-38
